(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={market:[],notices:[],accounts:[],profile:null};
function mode(){try{return window.GANIAppData?.mode?.()||"mock"}catch{return"mock"}}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toast(m){const t=$("#toast");if(!t)return;t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}
function show(id,push=true){if(!$("#"+id))id="home";$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-screen]').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));$('#mobileMenu')?.classList.remove('open');$('#noticePanel')?.classList.remove('open');$('#searchPanel')?.classList.remove('open');if(push)history.replaceState(null,"","#"+id);window.scrollTo({top:0,left:0,behavior:'auto'});if(id==='dashboard')loadDashboard();if(id==='profile')loadProfile();if(id==='discover')loadMarket()}
async function safe(fn){try{return await fn()}catch(e){toast(e?.message||'Data request failed');return null}}
function updateMode(){const m=mode().toUpperCase(),real=m==='REAL';['#dashMode','#profileMode','#homeMode'].forEach(s=>{const el=$(s);if(el)el.textContent=m});if($('#marketMode'))$('#marketMode').textContent=real?'REAL API':'DEMO DATA';if($('#heroMode'))$('#heroMode').textContent=real?'REAL API':'DEMO MODE';if($('#marketStripMode'))$('#marketStripMode').textContent=real?'API CONNECTED':'DEMO MODE';if($('#mobileMode'))$('#mobileMode').textContent=real?'REAL API':'DEMO MODE';if($('#mobileDataLabel'))$('#mobileDataLabel').textContent=real?'API connected':'Demo data'}
async function loadMarket(){const d=await safe(()=>GANIAppData.marketplace());if(!d)return;state.market=Array.isArray(d.items)?d.items:[];if($('#homeMarketCount'))$('#homeMarketCount').textContent=state.market.length;if($('#mobileMarketCount'))$('#mobileMarketCount').textContent=state.market.length;renderMarket()}
function renderMarket(){const el=$('#marketGrid');if(!el)return;const q=$('#marketSearch')?.value.trim().toLowerCase()||'';const items=state.market.filter(x=>JSON.stringify(x).toLowerCase().includes(q));el.innerHTML=items.length?items.map((x,i)=>`<article class="market-card"><span class="tag">${esc(x.mode||mode())}</span><h3>${esc(x.title||x.name||'GANI Marketplace')}</h3><p>${esc(x.summary||x.description||'Marketplace information available through GANI.')}</p><footer><span>Record ${i+1}</span><b>${esc(x.status||'Available')}</b></footer></article>`).join(''):`<article class="market-card"><span class="tag">SEARCH</span><h3>No matches</h3><p>Try a different keyword.</p><footer><span>0 results</span><b>Ready</b></footer></article>`}
async function loadNotices(){const d=await safe(()=>GANIAppData.notifications());if(!d)return;state.notices=Array.isArray(d.items)?d.items:[];renderNotices()}
function noticeHTML(n){return `<div class="notice-row ${n.read?'':'unread'}" data-notice="${esc(n.id)}"><div class="notice-icon">${n.read?'✓':'•'}</div><div><b>${esc(n.title||'Notification')}</b><small>${n.read?'Read':'Unread'}</small></div>${n.read?'':`<button class="status-pill read-one">Mark read</button>`}</div>`}
function renderNotices(){const h=state.notices.length?state.notices.map(noticeHTML).join(''):'<p class="hint">No notifications.</p>';if($('#noticeList'))$('#noticeList').innerHTML=h;if($('#dashboardNotices'))$('#dashboardNotices').innerHTML=h;const unread=state.notices.filter(n=>!n.read).length;if($('#unreadCount'))$('#unreadCount').textContent=unread;if($('#homeNoticeCount'))$('#homeNoticeCount').textContent=unread;if($('#mobileNoticeCount'))$('#mobileNoticeCount').textContent=unread;$('#noticeDot')?.classList.toggle('on',unread>0);$$('.read-one').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-notice]').dataset.notice;await safe(()=>GANIAppData.markNotificationRead(id));await loadNotices()})}
async function loadAccounts(){const d=await safe(()=>GANIAppData.accounts());if(!d)return;state.accounts=Array.isArray(d.items)?d.items:[];if($('#accountCount'))$('#accountCount').textContent=state.accounts.length;if($('#homeAccountCount'))$('#homeAccountCount').textContent=state.accounts.length;if($('#mobileAccountCount'))$('#mobileAccountCount').textContent=state.accounts.length;if($('#accountList'))$('#accountList').innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="account-row"><div class="account-icon">◎</div><div><b>${esc(a.name||a.id||'Account')}</b><small>${esc(a.provider||a.mode||'GANI')}</small></div><span class="status-pill">${esc(a.status||'active')}</span></div>`).join(''):'<p class="hint">No accounts available.</p>'}
async function loadProfile(){const p=await safe(()=>GANIAppData.me());if(!p)return;state.profile=p;const name=p.name||'GANI User';[['#profileName',name],['#profileName2',name],['#profileId',p.id||'—'],['#profileVerified',p.verified?'Verified':'Not verified'],['#verifiedBadge',p.verified?'✓ Verified':'Unverified'],['#profileState',p.verified?'Customer profile verified':'Customer profile'],['#profileSource',mode().toUpperCase()]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v})}
async function loadDashboard(){updateMode();await Promise.all([loadAccounts(),loadNotices()])}
async function verify(){const ref=$('#verifyInput').value.trim(),box=$('#verifyResult');if(!ref){toast('Enter a GANI reference');return}box.className='verify-result';box.innerHTML='<div class="skeleton"></div>';const r=await safe(()=>GANIAppData.verify(ref));if(!r){box.innerHTML='<div class="verify-ring"><span>!</span></div><small>VERIFICATION</small><h3>Unable to verify</h3><p>Check the data source and try again.</p>';return}const ok=String(r.status).toLowerCase()==='verified';box.className='verify-result '+(ok?'success':'fail');box.innerHTML=`<div class="verify-ring"><span>${ok?'✓':'!'}</span></div><small>VERIFICATION</small><h3>${ok?'Verified':'Not verified'}</h3><p>${esc(r.reference||ref)}</p><span class="status-pill ${ok?'':'neutral'}">${esc(r.mode||mode())}</span>`}
function bind(){
  $$('[data-screen]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();show(b.dataset.screen)}));
  $$('[role="button"][data-screen]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show(b.dataset.screen)}}));
  $('#menuToggle').onclick=()=>$('#mobileMenu').classList.toggle('open');
  $('#searchToggle').onclick=()=>{$('#searchPanel').classList.add('open');$('#globalSearch').focus()};
  $('#searchClose').onclick=()=>$('#searchPanel').classList.remove('open');
  $('#noticeToggle').onclick=()=>{$('#noticePanel').classList.toggle('open');loadNotices()};
  $('#noticeClose').onclick=()=>$('#noticePanel').classList.remove('open');
  $('#marketSearch').oninput=renderMarket;$('#verifyBtn').onclick=verify;$('#verifyInput').onkeydown=e=>{if(e.key==='Enter')verify()};
  $('#refreshDashboard').onclick=loadDashboard;
  $('#markAllRead').onclick=async()=>{for(const n of state.notices.filter(n=>!n.read))await safe(()=>GANIAppData.markNotificationRead(n.id));await loadNotices()};
  $('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();$('#searchPanel').classList.remove('open');if(q.includes('ver')||q.includes('tool'))show('verify');else if(q.includes('account')||q.includes('analytic')||q.includes('dash'))show('dashboard');else if(q.includes('profile'))show('profile');else if(q.includes('learn')||q.includes('edu'))show('education');else if(q.includes('support')||q.includes('help'))show('support');else{show('discover');$('#marketSearch').value=e.target.value;renderMarket()}}};
  window.addEventListener('hashchange',()=>show(location.hash.slice(1)||'home',false));
}
window.addEventListener('DOMContentLoaded',async()=>{bind();updateMode();show(location.hash.slice(1)||'home',false);await Promise.all([loadMarket(),loadNotices(),loadAccounts(),loadProfile()]);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();
